# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
     actions: read
     contents: write
     id-token: write
     
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v -o feather-binary ./cmd/fledge

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: feather-binary
        path: feather-binary

    - name: Install syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM
      run: syft feather -o spdx-json > syft-sbom.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: syft-sbom.json
        path: syft-sbom.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.8.1

    - name: Sign SBOM
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        cosign sign-blob --oidc-issuer https://token.actions.githubusercontent.com \
          --bundle syft-sbom.bundle \
          --yes \
          syft-sbom.json

    - name: Upload Bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: cosign-bundle
        path: syft-sbom.bundle

    - name: Verify signature (as a test)
      run: |
        cosign verify-blob \
        --bundle syft-sbom.bundle \
        --certificate-identity "https://github.com/jordithijsman/sbom-workshop-go/.github/workflows/go.yml@refs/heads/main" \
        --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
        syft-sbom.json

    
